config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  get 'books/import' => 'books#import'
  
  resources :books do
    collection {post :import}
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
require 'csv'
require 'activerecord-import/base'
require 'activerecord-import/active_record/adapters/postgresql_adapter'

class Book < ApplicationRecord

    validates :title, presence: true
    validates :firstname, presence: true
    validates :lastname, presence: true
    validates :gender, presence: true
    validates :published, length: {
        is: 4, 
        message: '- this must be a 4-digit year'}
    validates :rating, inclusion: {
        in: 1..5,
        message: '- this must be from 1 to 5'}

    enum gender: [:Female, :Male, :Other]
   
    def owned_yn
        :owned ? 'Yes' : 'No'
    end

    def self.my_import(file)
        new_books = []
        header_converter = lambda { |header| header.downcase }
        CSV.foreach(file.path, headers: true, header_converters: header_converter) do |row|
                row['gender'] = row['gender'] == 'F' ? 0 : 1
                new_books << Book.new(row.to_h)
            end
        Book.import new_books, recursive: true
    end

    #TAGS
    has_many :taggings
    has_many :tags, through: :taggings
  

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :books, through: :taggings
      
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    include Pagy::Backend

    USER = ENV['CONTROLLER_USER']
    PASS = ENV['CONTROLLER_PASSWORD']    

    before_action :authenticate, except: [:index]
    
    helper_method :sort_column, :sort_direction, :null_order

    def index
        unlowered = "#{sort_column} #{sort_direction} #{null_order}"
        lowered = "lower(#{sort_column}) #{sort_direction} #{null_order}"
        @date_start ||= Date.new(Date.current.year,1,1)
        @date_finish = Date.new(params['date_end'].to_i)
        #test = Date.new(params['date_end'].to_i)
        @pagy, @books = pagy(Book.where(finished: @date_start..@date_end).order(['title', 'lastname', 'series'].include?(sort_column) ? lowered : unlowered), items: 50)
    end

    def show
        @book = Book.find(params[:id])
    end

    def new
        @book = Book.new
    end

    def edit
        @book = Book.find(params[:id])
    end      

    def create
        @book = Book.new(book_params)
       
        if @book.save
            redirect_to @book
        else
            render 'new'
        end
    end

    def update
        @book = Book.find(params[:id])

        if @book.update(book_params)
            redirect_to @book
        else
            render 'edit'
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy

        redirect_to books_path
    end

    def import
        if params[:file]
            before = Book.count
            Book.my_import(params[:file])
            added = Book.count - before
            flash[:notice] = "Added #{added} new books"
            redirect_to books_path 
        else
            flash[:notice] = "No file selected"
            redirect_to new_book_path
        end
    end

    private
    def book_params
        params.require(:book).permit(
            :title, 
            :firstname, 
            :lastname, 
            :rating,
            :gender,
            :published, 
            :finished, 
            :series,
            :owned)
    end

    def sort_column
        Book.column_names.include?(params[:sort]) ? params[:sort] : "finished"
    end
      
    def sort_direction
        ['asc', 'desc'].include?(params[:direction]) ? params[:direction] : "desc"
    end
    
    def null_order
        ['nulls first', 'nulls last'].include?(params[:null_order]) ? params[:null_order] : "nulls last"
    end

    def authenticate
        unless request.env['HTTP_HOST'] == 'localhost:3000'
            http_basic_authenticate_with name: USER, password: PASS, except: [:index]
        end
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        today = Date.current
        @this_year = Book.where(:finished => Date.new(today.year,1,1)..today)
        @this_month_count = @this_year.where(:finished => Date.new(today.year,today.month,1)..today).count 
        @this_year_count = @this_year.count
        
        if @this_year_count > 0
            @women_this_year = (100*@this_year.where(gender: 0).count/@this_year_count).round
        else
            @women_this_year = 0
        end

        @all_time_count = Book.where.not(finished: nil).count
        @chart1 = Book.where(finished: "2011-01-01"..).group_by_year(:finished, format: "%Y").count

    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
    include Pagy::Frontend
    
    def sortable(column, title = nil)
        title ||= column.titleize
        # the lines below flip it if you click on the col you're already sorting by
        direction = (column == sort_column() && sort_direction() == "asc") ? "desc" : "asc"
        null_order = (column == sort_column() && null_order() == "nulls first") ? "nulls last" : "nulls first"
        link_to title, sort: column, direction: direction, null_order: null_order
    end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>

    <% if @book.errors.any? %>
        <div id="error_explanation">
            <h3>
                <%= pluralize(@book.errors.count, "error") %> stopped you saving this book:
            </h3>
            <ul>
            <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :firstname, "Author's first name" %><br>
        <%= form.text_field :firstname %>
    </p>

    <p>
        <%= form.label :lastname, "Author's last name" %><br>
        <%= form.text_field :lastname %>
    </p>

    <p>
        <%= form.label :rating %><br>
        <%= form.number_field :rating, min: 1, max: 5, placeholder: 3 %>
    </p>

    <p>
        <%= form.label :gender, "Author's gender" %><br>
        <%= form.select :gender, Book.genders.keys, {} %>
    </p>

    <p>
        <%= form.label :published, "Year published" %><br>
        <%= form.text_field :published %>
    </p>

    <p>
        <%= form.label :finished, "Date finished" %><br>
        <%= form.date_field :finished, :value => Date.current %>
    </p>

    <p>
        <%= form.label :series %><br>
        <%= form.text_field :series %>
    </p>

    <p>
        Do I own it? <%= form.check_box :owned %><br>
    </p>

    <p>
        <%= form.submit "Add book" %>
    </p>

<% end %>

app/views/books/edit.html.erb
<h1>Edit a book</h1>
 
<%= link_to 'Back to books list', books_path %><p>
<%= link_to 'Back to dashboard', "/" %><p>

<%= render 'form' %>

 

app/views/books/import.html.erb
<% flash[:notice] %>
<div>
    <h2>Import data</h2>
    <% form_tag import_books_path, multipart: true do %>
        <% file_field_tag :file %>
        <% submit_tag "Import from file" %>
    <% end %>
</div>
<table>
    <thead>
        <tr>
            <th>Lastname</th>
            <th>Firstname</th>
            <th>Title</th>
            <th>Gender</th>
            <th>Series</th>
            <th>Rating</th>
            <th>Year</th>
            <th>Finished</th>
            <th>Owned</th>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><% book.lastname %></td>
            <td><% book.firstname %></td>
            <td><% book.title %></td>
            <td><% book.gender %></td>
            <td><% book.series %></td>
            <td><% book.rating %></td>
            <td><% book.published %></td>
            <td><% book.finished %></td>
            <td><% book.owned %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/books/index.html.erb
<h1>What I've read</h1>

<% if flash[:notice] %>
    <div class = "notice"><%= flash[:notice] %></div>
<% end %>

<%= link_to 'Back to dashboard', "/" %><p>
<%= link_to 'Add a new book', new_book_path %><p> 

<%= pagy_nav(@pagy).html_safe %>

<p>Showing books up to:</p>

<%= date_select(:date_end, order: [:year, :month, :day], prompt: 'End date') %>

<table>
    <tr>
        <th><%= sortable("title") %></th>
        <th><%= sortable("lastname", "Author") %></th>
        <th><%= sortable("gender", "Author's gender") %></th>
        <th><%= sortable("rating") %></th>
        <th><%= sortable("published", "Year published") %></th>
        <th><%= sortable("finished", "Date finished") %></th>
        <th><%= sortable("series") %></th>
        <th><%= sortable("owned") %></th>
        <th colspan = "2"></th>
    </tr>

    <% @books.each do |book| %>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.lastname %>, <%= book.firstname %></td>
            <td><%= book.gender %></td>
            <td><%= book.rating %></td>
            <td><%= book.published %></td>
            <td><%= book.finished %></td>
            <td><%= book.series %></td>
            <td><%= book.owned_yn %></td>
            <td><%= link_to 'Edit', edit_book_path(book) %></td>
            <td><%= link_to 'Destroy', book_path(book),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>

</table>

<%= pagy_nav(@pagy).html_safe %>

app/views/books/new.html.erb
<h1>Enter new books</h1>

<p><%= link_to 'Back to dashboard', "/" %></p>
<p><%= link_to 'Back to book list', books_path %></p>

<% if flash[:notice] %>
    <div class = "notice"><%= flash[:notice] %></div>
<% end %>
<br>
<h2>Add a new book</h2>
<%= render 'form' %>

<div>
    <h2>Import CSV of books</h2>
    <%= form_tag import_books_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import from CSV" %>
    <% end %>
</div>

app/views/books/show.html.erb
<h1>Book added</h1>

<%= link_to 'Back to book list', books_path %><p>

<p>
    <strong>Title:</strong>
    <%= @book.title %>
</p>

<p>
    <strong>Author's first name:</strong>
    <%= @book.firstname %>
</p>

<p>
    <strong>Author's last name:</strong>
    <%= @book.lastname %>
</p>

<p>
    <strong>Rating:</strong>
    <%= @book.rating %>
</p>

<p>
    <strong>Author's gender:</strong>
    <%= @book.gender %>
</p>

<p>
    <strong>Year published:</strong>
    <%= @book.published %>
</p>

<p>
    <strong>Date finished:</strong>
    <%= @book.finished.strftime("%-d %B %Y") %>
</p>

<p>
    <strong>Series:</strong>
    <%= @book.series %>
</p>

<p>
    <strong>Owned?</strong>
    <%= @book.owned %>
</p>

app/views/home/index.html.erb
<h1>Hello!</h1>
<p>This is the dashboard for my reading app</p>

<%= link_to "Add new book", new_book_path %><p>
<%= link_to "List all the books I've read", books_path %><p>

<p><strong><%= @this_month_count %></strong> books finished this month</p>
<p><strong><%= @this_year_count %></strong> books finished this year</p>
<p><strong><%= @women_this_year %>%</strong> of books read this year were by women</p>
<p><strong><%= @all_time_count %></strong> books read since I started recording in 2011</p>

<h2>Books read per year</h2>
<%= column_chart @chart1 %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reading</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>